environment:
  CONFIGURATION: Release
  TARGET: Default

  NUGET_SERVER_URL: https://www.nuget.org/api/v2/package
  NUGET_SYMBOL_SERVER_URL: https://nuget.smbsrc.net/api/v2/package
  NUGET_API_KEY:
    secure: EA06oAdAgaBCIJtU3ArzLp8uYgXBtEtZXoBqQGhxvgOJcxiSahALa4cpn31H85eh

  MYGET_SERVER_URL: https://www.myget.org/F/fairycode-ci/api/v2/package
  MYGET_SYMBOL_SERVER_URL: https://www.myget.org/F/fairycode-ci/symbols/api/v2/package
  MYGET_API_KEY:
    secure: 0lDXR8Vfp0v0azE55fJ/gfXnZ9JfFcokOtBGJgaqGB1zYgzPX4H0op+rQEf3j6UE

init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -target $env:TARGET -configuration $env:CONFIGURATION

# tests are run by build script
test: off

branches:
  only:
    - master

cache:
- tools -> build.cake
