environment:
  CONFIGURATION: Release
  TARGET: Default

  NUGET_API_URL: https://www.nuget.org/api/v2/package
  NUGET_API_KEY:
    secure: EA06oAdAgaBCIJtU3ArzLp8uYgXBtEtZXoBqQGhxvgOJcxiSahALa4cpn31H85eh

init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -target $env:TARGET -configuration $env:CONFIGURATION

# tests are run by build script
test: off

branches:
  only:
    - master

cache:
- tools -> build.cake
